export const ACTIONS = {
    ADD: "ADD_TRANSACTION",
    DELETE: "DELETE_TRANSACTION",
    UPDATE: "UPDATE_TRANSACTION",
    SET_ACTIVE: "SET_ACTIVE_TRANSACTION",
    RESET_SELECTED: "RESET_SELECTED_TRANSACTION"
};

